apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: django-migrate
        image: docker.io/app/django_app:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: django-config
      restartPolicy: Never