apiVersion : v1
kind : Service
metadata :
  name : django-service
  labels :
    env : prod
spec :
  selector :
    project : dj-app
  ports :
    - name : django-listener
      port : 8888
      targetPort : 80
      protocol : TCP
  type : LoadBalancer
